<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (C) 2024 Evolved Binary Ltd

    Changes made by Evolved Binary are proprietary and are not Open Source.

    NOTE: Parts of this file contain code from The eXist-db Authors.
          The original license header is included below.

    ======================================================================

    eXist-db Open Source Native XML Database
    Copyright (C) 2001 The eXist-db Authors

    info@exist-db.org
    http://www.exist-db.org

    This library is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public
    License as published by the Free Software Foundation; either
    version 2.1 of the License, or (at your option) any later version.

    This library is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with this library; if not, write to the Free Software
    Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA

-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    
    <parent>
        <groupId>org.exist-db</groupId>
        <artifactId>exist-parent</artifactId>
        <version>7.0.0-SNAPSHOT</version>
        <relativePath>../../../exist-parent</relativePath>
    </parent>
    
    <artifactId>exist-index-lucene</artifactId>
    <packaging>jar</packaging>
    
    <name>eXist-db Lucene Index</name>
    <description>eXist-db NoSQL Database Lucene Index</description>
    
    <scm>
        <connection>scm:git:https://github.com/exist-db/exist.git</connection>
        <developerConnection>scm:git:https://github.com/exist-db/exist.git</developerConnection>
        <url>scm:git:https://github.com/exist-db/exist.git</url>
      <tag>HEAD</tag>
  </scm>
    
    <dependencies>
        <dependency>
            <groupId>org.exist-db</groupId>
            <artifactId>exist-core</artifactId>
            <version>${project.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-collections4</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
        </dependency>
        
        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-core</artifactId>
            <version>${lucene.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analysis-common</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-analysis-icu</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-facet</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-queries</artifactId>
            <version>${lucene.version}</version>
        </dependency>
        
        <dependency>
            <groupId>org.apache.lucene</groupId>
            <artifactId>lucene-queryparser</artifactId>
            <version>${lucene.version}</version>
        </dependency>

        <dependency>
            <groupId>com.evolvedbinary.j8fu</groupId>
            <artifactId>j8fu</artifactId>
        </dependency>

        <dependency>
            <groupId>io.lacuna</groupId>
            <artifactId>bifurcan</artifactId>
        </dependency>

        <dependency>
            <groupId>it.unimi.dsi</groupId>
            <artifactId>fastutil</artifactId>
        </dependency>

        <dependency>
            <groupId>net.sf.xmldb-org</groupId>
            <artifactId>xmldb-api</artifactId>
        </dependency>

        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
        </dependency>

        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
        </dependency>

        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.xmlunit</groupId>
            <artifactId>xmlunit-legacy</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.googlecode.junit-toolbox</groupId>
            <artifactId>junit-toolbox</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.exist-db</groupId>
            <artifactId>exist-samples</artifactId>
            <version>${project.version}</version>
            <scope>test</scope>
        </dependency>

    </dependencies>

    <build>

        <testResources>
            <testResource>
                <directory>src/test/resources</directory>
                <filtering>false</filtering>
            </testResource>
            <testResource>
                <directory>src/test/resources-filtered</directory>
                <filtering>true</filtering>
            </testResource>
        </testResources>

        <plugins>
            <plugin>
                <groupId>com.mycila</groupId>
                <artifactId>license-maven-plugin</artifactId>
                <inherited>true</inherited>
                <configuration>
                        <licenseSets>
                            <licenseSet>
                                <header>${project.parent.relativePath}/LGPL-21-license.template.txt</header>
                                <excludes>
                                    <exclude>pom.xml</exclude>
                                    <exclude>**/README.md</exclude>
                                    <exclude>**/README</exclude>
                                    <exclude>**/LICENSE</exclude>
                                    <exclude>**/*.xar</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/analyzers/NoDiacriticsStandardAnalyzer.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/LuceneUtil.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/ExistFacetsCollector.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/AnalyzerConfig.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/XMLToQuery.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/LuceneFieldConfig.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/BinaryTokenStream.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/analyzers/NoDiacriticsStandardAnalyzer.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/ClassicQueryParserWrapper.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/LuceneIndex.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/LuceneIndexConfig.java</exclude>
                                    <include>src/main/java/org/exist/indexing/lucene/ExistLuceneTextField.java</include>
                                    <exclude>src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java</exclude>
                                    <exclude>src/main/java/org/exist/indexing/lucene/BoostField.java</exclude>
                                    <exclude>src/test/java/org/exist/indexing/lucene/AnalyzerConfigTest.java</exclude>
                                    <exclude>src/test/java/org/exist/indexing/lucene/analyzers/NoDiacriticsStandardAnalyzerTest.java</exclude>
                                    <include>src/test/java/org/exist/indexing/lucene/analyzers/AdHocAnalysersTest.java</include>
                                    <exclude>src/test/xquery/lucene/analyzers.xml</exclude>
                                    <exclude>src/test/xquery/lucene/FT_AttTest_complex.xml</exclude>
                                    <exclude>src/test/xquery/lucene/indirectQueriesTest.xml</exclude>
                                    <exclude>src/test/xquery/lucene/inline.xml</exclude>
                                    <exclude>src/test/xquery/lucene/LuceneFT+range_indexRetrievalTest.xml</exclude>
                                    <exclude>src/test/xquery/lucene/matchHighlighting_ftquery_Tests.xml</exclude>
                                    <exclude>src/test/xquery/lucene/parenthesizedContext_ftquery_Tests.xml</exclude>
                                    <exclude>src/test/xquery/lucene/queries.xml</exclude>
                                    <exclude>src/test/xquery/lucene/startOffset.xml</exclude>
                                </excludes>
                            </licenseSet>

                            <licenseSet>
                                <multi>
                                    <header>${project.parent.relativePath}/Elemental-licence.template.txt</header>
                                    <separator>======================================================================</separator>
                                    <header>${project.parent.relativePath}/LGPL-21-license.template.txt</header>
                                </multi>
                                <includes>
                                    <include>pom.xml</include>
                                    <include>src/test/xquery/lucene/analyzers.xml</include>
                                    <include>src/test/xquery/lucene/FT_AttTest_complex.xml</include>
                                    <include>src/test/xquery/lucene/indirectQueriesTest.xml</include>
                                    <include>src/test/xquery/lucene/inline.xml</include>
                                    <include>src/test/xquery/lucene/LuceneFT+range_indexRetrievalTest.xml</include>
                                    <include>src/test/xquery/lucene/matchHighlighting_ftquery_Tests.xml</include>
                                    <include>src/test/xquery/lucene/parenthesizedContext_ftquery_Tests.xml</include>
                                    <include>src/test/xquery/lucene/queries.xml</include>
                                    <include>src/test/xquery/lucene/startOffset.xml</include>
                                </includes>
                            </licenseSet>

                            <licenseSet>
                                <multi>
                                    <header>${project.parent.relativePath}/Elemental-licence.template.txt</header>
                                    <header>${project.parent.relativePath}/LGPL-21-license.template.txt</header>
                                </multi>
                                <includes>
                                    <include>src/main/java/org/exist/indexing/lucene/analyzers/NoDiacriticsStandardAnalyzer.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/LuceneUtil.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/AnalyzerConfig.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/XMLToQuery.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/LuceneFieldConfig.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/BinaryTokenStream.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/analyzers/NoDiacriticsStandardAnalyzer.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/LuceneIndexWorker.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/ClassicQueryParserWrapper.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/LuceneIndex.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/LuceneIndexConfig.java</include>
                                    <include>src/main/java/org/exist/xquery/modules/lucene/QueryOptions.java</include>
                                    <include>src/test/java/org/exist/indexing/lucene/AnalyzerConfigTest.java</include>
                                </includes>
                            </licenseSet>
                            <licenseSet>
                                <header>${project.parent.relativePath}/Elemental-licence-new-code.template.txt</header>
                                <includes>
                                    <include>src/main/java/org/exist/indexing/lucene/ExistFacetsCollector.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/ExistLuceneTextField.java</include>
                                    <include>src/main/java/org/exist/indexing/lucene/BoostField.java</include>
                                    <include>src/test/java/org/exist/indexing/lucene/analyzers/NoDiacriticsStandardAnalyzerTest.java</include>
                                    <include>src/test/java/org/exist/indexing/lucene/analyzers/AdHocAnalysersTest.java</include>
                                </includes>
                            </licenseSet>
                        </licenseSets>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>analyze</id>
                        <goals>
                            <goal>analyze-only</goal>
                        </goals>
                        <configuration>
                            <failOnWarning>true</failOnWarning>
                            <ignoredUnusedDeclaredDependencies>
                                <ignoredUnusedDeclaredDependency>org.apache.lucene:lucene-queries:jar:${lucene.version}</ignoredUnusedDeclaredDependency>  <!-- needed at runtime to support lucene query syntax -->
                                <ignoredUnusedDeclaredDependency>org.junit.vintage:junit-vintage-engine:jar</ignoredUnusedDeclaredDependency>
                            </ignoredUnusedDeclaredDependencies>

                            <ignoredUsedUndeclaredDependencies>
                                <ignoredUsedUndeclaredDependency>com.ibm.icu:icu4j:jar</ignoredUsedUndeclaredDependency>
                            </ignoredUsedUndeclaredDependencies>

                            <ignoredNonTestScopedDependencies>
                                <ignoredNonTestScopedDependency>net.sf.xmldb-org:xmldb-api:jar</ignoredNonTestScopedDependency>
                            </ignoredNonTestScopedDependencies>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    
</project>
